# Accept the Go version for the image to be set as a build argument.
# Default to Go 1.11
ARG GO_VERSION=1.11.4

# First stage: build the executable.
FROM golang:1.11.4-alpine
# Install the Certificate-Authority certificates for the app to be able to make
# calls to HTTPS endpoints.
RUN apk add --no-cache ca-certificates git

# Set the environment variables for the go command:
ENV GOFLAGS=-mod=vendor GOOS=linux GOARCH=amd64

# Set the working directory outside $GOPATH to enable the support for modules.
WORKDIR /src

# Import the code from the context.
ADD ./ ./

EXPOSE 8000