apiVersion: v1
kind: ConfigMap
metadata:
  namespace: default
  name: helloworld-config
  labels:
    name: env
    environment: development
data:
  POSTGRES_HOST: postgres
  POSTGRES_PORT: "5432"
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: practice

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: helloworld
  namespace: default
  labels:
    app: helloworld
    environment: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld
        image: vuchauthanh/helloworld
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        readinessProbe:
          httpGet:
            path: /
            port: 8000
        envFrom:
        - configMapRef:
            name: helloworld-config

---
kind: Service
apiVersion: v1
metadata:
  name: helloworld
  namespace: default
  labels:
    app: helloworld
    environment: development
spec:
  selector:
    app: helloworld
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000