apiVersion: v1
kind: ConfigMap
metadata:
  name: helloworld-config
  namespace: default
data:
  NEW_FEATURE: "true"
---

apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: helloworld
  namespace: default
  labels:
    app: helloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld
        image: vuchauthanh/helloworld
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        readinessProbe:
          httpGet:
            path: /
            port: 8000
        envFrom:
        - configMapRef:
            name: helloworld-config

---

kind: Service
apiVersion: v1
metadata:
  name: helloworld
  namespace: default
spec:
  selector:
    app: helloworld
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000